services:
  mysql-test:
    image: mysql:8.0
    container_name: dbi-cp_test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    command: --max_allowed_packet=1048576
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  postgresql-test:
    image: postgres:16
    container_name: dbi-cp_test_postgresql
    environment:
      POSTGRES_USER: dbicp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    tmpfs:
      - /var/lib/postgresql/data
      - /var/log
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbicp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
